/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kinematics_JniKinematics */

#ifndef _Included_kinematics_JniKinematics
#define _Included_kinematics_JniKinematics
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kinematics_JniKinematics
 * Method:    solveIKNative
 * Signature: (DDD[[D[DZ)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_kinematics_JniKinematics_solveIKNative
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jobjectArray, jdoubleArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
